-- 1. Extensions ---------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Tables -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_message (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    author     varchar(128) NOT NULL,
    message    text         NOT NULL,
    embedding  vector(1536)
);

-- 3. Indexes ------------------------------------------------------------------
-- Approximate-nearest-neighbour index for cosine similarity search
-- (matches the `embedding <=> :q` operator used in ChatMessageRepository).
CREATE INDEX IF NOT EXISTS idx_chat_message_embedding_hnsw
    ON chat_message
    USING hnsw (embedding vector_cosine_ops);

-- Common access patterns: recent messages, per-author history.
CREATE INDEX IF NOT EXISTS idx_chat_message_created_at
    ON chat_message (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_message_author_created_at
    ON chat_message (author, created_at DESC);

